llm:
  model: "gpt-4-1106-preview"
  temperature: 0.1
  max_retries: 2
fallback_llm:
  model: "gpt-4-1106-preview"
  temperature: 0.1
  max_retries: 6
embeddings:
  type: "OpenAIEmbedding"
  config:
    embeddings_model: "text-embedding-ada-002"
    embedding_dim: 512
retrieval_re_ranker:
  enabled: True
use_you_search_api:
  enabled: True
query_enhancer_followed_by_rerank_fusion:
  enabled: True
chunk_size: 512
top_k: 5
