llm:
  model: "gpt-4-0125-preview" # 1106 1.1
  temperature: 0.1
  max_retries: 2
fallback_llm:
  model: "gpt-4-0125-preview"
  temperature: 0.1
  max_retries: 6
embeddings:
  type: "OpenAIEmbedding"
  config:
    embeddings_model: "text-embedding-3-small" # text-embedding-ada-002
    embedding_dim: 512
retrieval_re_ranker:
  enabled: True
use_you_search_api:
  enabled: True
query_enhancer:
  enabled: True
rerank_fusion:
  enabled: True
chunk_size: 512
top_k: 5
