llm:
  model: "gpt-4-1106-preview"
  temperature: 0.1
  max_retries: 2
fallback_llm:
  model: "gpt-3.5-turbo-1106"
  temperature: 0.1
  max_retries: 6
embeddings:
  type: "MistralEmbedding"
  config:
    embeddings_model: "mistral/mistral-embed"
retrieval_re_ranker:
  enabled: False
use_you_search_api:
  enabled: False
query_enhancer_followed_by_rerank_fusion:
  enabled: True
chunk_size: 1024
top_k: 5
