llm: "gpt-4-1106-preview"
embeddings:
  type: "OpenAIEmbedding"
  config:
    embeddings_model: "text-embedding-3-small"
    embedding_dim: 512
retrieval_re_ranker:
  enabled: true
use_you_search_api:
  enabled: true
query_enhancer_followed_by_rerank_fusion:
  enabled: true
chunk_size: 512
top_k: 5
